# The URL the site will be built for
base_url = "https://zolaongcp.com"

title = "Zola on Google Cloud"
description = "Turn-key deploy static Zola site on Google Cloud"

theme = "serene"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
generate_feeds = false
feed_filenames = ["feed.xml"]
taxonomies = [{ name = "tags" }, { name = "categories" }]


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
# Put all your custom variables here
name = "Zola on Google Cloud"
id = "Zola on GCP"
display_id = false
display_bio = false
display_avatar = false

recent = false
recent_max = 5
recent_more_text = "more »"

sections = [
    { name = "posts", path = "/posts", is_external = false },
    # { name = "about", path = "/about", is_external = false },
    { name = "github", path = "https://github.com/tonivanhala/zolaongcp.com", is_external = true },
]
blog_section_path = "/posts"

links = [
    { name = "GitHub", icon = "github", url = "https://github.com/tonivanhala" },
]

force_theme = false
blog_categorized = true               # Whether to categorize blog posts
blur_effect = false                   # Whether to turn on blur effect on navigation bar
back_to_top = true                    # Whether to show back-to-top button on post pages
toc = true                            # Whether to show Table-of-Contents by default
copy = true                           # Whether to add a copy button on code blocks by default
display_tags = true                   # Whether to display tags on post pages by default
truncate_summary = false              # Whether to truncate the summary of a post by default
comment = false                       # Whether to show giscus comment section by default, see https://giscus.app for more info

reaction = false    

outdate_alert = false                 # Whether to show outdate alert by default
outdate_alert_days = 120

nav_separator = "::"
nav_wrapper_left = "{"
nav_wrapper_right = "} ;"
nav_wrapper_separator = ","

footer_copyright = "© 2025 Toni Vanhala"
footer_credits = true                 # Whether to show "powered by zola and serene" in footer

not_found_title = "404"
not_found_error_text = "Not Found"
not_found_recover_text = "« back to home »"
