on:
  push:
    branches:
      - main
    paths:
      - 'site/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          submodules: recursive
      - uses: taiki-e/install-action@87b5304d4e82236718783683826c899da7e5470f
        with:
          tool: zola@0.20.0
      - name: Build site
        working-directory: ./site
        run: zola build
      - name: Google Authentication
        uses: 'google-github-actions/auth@71f986410dfbc7added4569d411d040a91dc6935'
        with:
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          project_id: '${{ secrets.GOOGLE_PROJECT_ID }}'
      - id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@7c6e11cb7291594c5dfe0bc1dd9cd905e31e600c'
        with:
          path: './site/public'
          destination: '${{ secrets.WEBSITE_BUCKET }}'
          parent: false
          process_gcloudignore: false
