on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.20.0
      - name: Build site
        working-directory: ./site
        run: zola build
      - name: Google Authentication
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          project_id: '${{ secrets.GOOGLE_PROJECT_ID }}'
      - id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: './site/public'
          destination: '${{ secrets.WEBSITE_BUCKET }}'
          parent: false
          process_gcloudignore: false
